Atualizando flask-oauthlib pois está quebrando os testes
Por algum motivo, com a flask-oauthlib==0.9.4 os testes não rodam, por
esse erro:

```
>>> from tests import test_app
/home/daltonmatos/.local/share/virtualenvs/asgard-api-YwspFh3W/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daltonmatos/src/asgard-api/tests/test_app.py", line 8, in <module>
    from hollowman.app import application
  File "/home/daltonmatos/src/asgard-api/hollowman/app.py", line 87, in <module>
    import hollowman.routes
  File "/home/daltonmatos/src/asgard-api/hollowman/routes.py", line 8, in <module>
    from hollowman.auth.google import google_oauth2
  File "/home/daltonmatos/src/asgard-api/hollowman/auth/google.py", line 3, in <module>
    from flask_oauthlib.client import OAuth
  File "/home/daltonmatos/.local/share/virtualenvs/asgard-api-YwspFh3W/lib/python3.6/site-packages/flask_oauthlib/client.py", line 20, in <module>
    from .utils import to_bytes
  File "/home/daltonmatos/.local/share/virtualenvs/asgard-api-YwspFh3W/lib/python3.6/site-packages/flask_oauthlib/utils.py", line 5, in <module>
    from oauthlib.common import to_unicode, bytes_type
ImportError: cannot import name 'bytes_type'
```

Atualizando para o flask-oauthlib==0.9.5 o problema não acontece mais e
os testes continuam passando.